[custom]
enable_insert=true
prepend_insert_url=true
enable_rule_generator=true
overwrite_original_rules=true
skip_failed_links=true
enable_cache = false
;clash_rule_base=base/forcerule.yml
quanx_rule_base = https://fastly.jsdelivr.net/gh/zhouyining-stat/subconverter-clash@main/quanx.conf
loon_rule_base = https://raw.githubusercontent.com/zhouyining-stat/subconverter-clash/main/loon.conf
;singbox_rule_base = https://raw.githubusercontent.com/senzyo/sing-box-templates/public/tun/https/ali/google/testingcf.jsdelivr.net/config_apple.json
#过滤节点，正则匹配
;exclude_remarks=(tuic|白嫖|过期|重置|流量|用户|本站|漏洞|永久虚通路|车|邀|免翻|邀请|eevpn|域名|机场|刷新|禁止|备用登录|计划|面板|忘记|到期|套餐|官网|更多|关注|25倍率|http|增加|持续|渠道|购买|QQ|Ins|二手)


ruleset=🎯 全球直连,https://fastly.jsdelivr.net/gh/zhouyining-stat/subconverter-clash@main/direct.list
ruleset=🎯 全球直连,https://fastly.jsdelivr.net/gh/zhouyining-stat/subconverter-clash@main/AICN.list
ruleset=📖 学术直连,https://fastly.jsdelivr.net/gh/zhouyining-stat/subconverter-clash@main/scholar_dir.list
ruleset=📖 学术网站,https://fastly.jsdelivr.net/gh/zhouyining-stat/subconverter-clash@main/scholar.list
ruleset=🌍 国外媒体,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.list
ruleset=🌍 国外媒体,https://fastly.jsdelivr.net/gh/zhouyining-stat/subconverter-clash@main/ex_media.list
ruleset=📖 谷歌search,https://fastly.jsdelivr.net/gh/zhouyining-stat/subconverter-clash@main/GoogleSearch.list
ruleset=📖 谷歌,https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Gemini/Gemini.list
ruleset=📖 谷歌,https://fastly.jsdelivr.net/gh/zhouyining-stat/subconverter-clash@main/google_scholar.list
ruleset=📖 谷歌,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.list
ruleset=🔥 Cloudflare,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Cloudflare/Cloudflare.list
ruleset=🤖 OpenAI,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.list
ruleset=🤖 OpenAI,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Claude/Claude.list
ruleset=🤖 OpenAI,https://github.com/blackmatrix7/ios_rule_script/raw/refs/heads/master/rule/Clash/Copilot/Copilot.list
ruleset=❌ exHK,https://fastly.jsdelivr.net/gh/zhouyining-stat/subconverter-clash@main/ex_proxy_new.list
ruleset=🍎 苹果代理,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AppleProxy/AppleProxy.list
ruleset=🍎 苹果服务,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.list
;ruleset=📢 谷歌FCM,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GoogleFCM/GoogleFCM.list
ruleset=🛑 全球拦截,https://fastly.jsdelivr.net/gh/zhouyining-stat/subconverter-clash@main/ex_ad.list
ruleset=🛑 全球拦截,https://github.boki.moe/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-QuantumultX.list
;ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
;ruleset=🛑 全球拦截,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/AdvertisingLite/AdvertisingLite.list
ruleset=☎️ 电报,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.list
ruleset=📦 github,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub.list
ruleset=📝 vscode,https://fastly.jsdelivr.net/gh/zhouyining-stat/subconverter-clash@main/vscode.list
ruleset=💬 微信,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/WeChat/WeChat.list
ruleset=🐧 腾讯,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Tencent/Tencent.list
ruleset=📺 批哩批哩,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/BiliBili/BiliBili.list
ruleset=🥝 爱奇艺,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/iQIYI/iQIYI.list
ruleset=🍠 小红书,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XiaoHongShu/XiaoHongShu.list
ruleset=🕺 字节跳动,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ByteDance/ByteDance.list
ruleset=💃 TikTok,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok.list
ruleset=🥭 芒果tv,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HunanTV/HunanTV.list
ruleset=🎮 米哈游,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/HoYoverse/HoYoverse.list
ruleset=🎮 米哈游,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/GameDownloadCN/GameDownloadCN.list
ruleset=📰 微博,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Weibo/Weibo.list
ruleset=💰 阿里巴巴,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Alibaba/Alibaba.list
ruleset=📱 小米,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/XiaoMi/XiaoMi.list
;ruleset=📱 华为,https://github.com/blackmatrix7/ios_rule_script/blob/master/rule/Clash/Huawei/Huawei.list
;ruleset=📱 Vivo,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Vivo/Vivo.list
;ruleset=📱 Oppo,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OPPO/OPPO.list
ruleset=📱 联想,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lenovo/Lenovo.list
;ruleset=📱 一加,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OnePlus/OnePlus.list
;ruleset=📱 魅族,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/MeiZu/MeiZu.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/SteamCN/SteamCN.list
;ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.list
ruleset=🎯 全球直连,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/OneDrive/OneDrive.list
ruleset=🚀 节点选择,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Proxy/Proxy.list
ruleset=🚀 节点选择,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Twitter/Twitter.list
;ruleset=🚀 节点选择,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ProxyLite/ProxyLite.list
;ruleset=🚀 节点选择,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/EA/EA.list
;ruleset=🚀 节点选择,https://fastly.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Origin/Origin.list
;ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=🎯 全球直连,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaIPs/ChinaIPs.list
ruleset=🚀 节点选择,https://fastly.jsdelivr.net/gh/zhouyining-stat/subconverter-clash@main/ex_proxy.list


ruleset=🎯 全球直连,[]GEOIP,private
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]👑 VIP`[]🔥 CF最优`[]❌ exHK`[]🇺🇸 美国节点`[]🇭🇰 香港节点`[]📖 学术SELF`[]🥵 我的节点`^(?!.*(YNU|NENU)).*$
custom_proxy_group=👑 VIP`url-test`(VIP)`http://www.gstatic.com/generate_204`3600,,100
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`3600,,100
custom_proxy_group=🔥 CF最优`url-test`(CF官方优选)`http://www.gstatic.com/generate_204`3600,,100
custom_proxy_group=🌍 国外媒体`select`[]🌍 最优媒体`[]🔥 CF最优`[]👑 VIP`[]🚀 节点选择`[]❌ exHK`[]🇺🇸 美国节点`[]🇭🇰 香港节点
custom_proxy_group=🌍 最优媒体`url-test`(HK|港|hk|Hong|Taiwan|🇹🇼|Japan|台|日|🇯🇵|新加坡|🇸🇬)`https://www.youtube.com/generate_204`3600,,100
;custom_proxy_group=Ⓜ️ 微软服务`select`[]🎯 全球直连`[]🚀 节点选择`.*
custom_proxy_group=🍎 苹果代理`select`[]🎯 全球直连`[]🚀 节点选择`[]❌ exHK`[]🇺🇸 美国节点`[]🇭🇰 香港节点
custom_proxy_group=🍎 苹果服务`select`[]🎯 全球直连`[]🚀 节点选择`[]❌ exHK`[]🇺🇸 美国节点`[]🇭🇰 香港节点
;custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=📖 谷歌`select`[]🏠 家宽节点`[]🔥 CF最优`[]👑 VIP`[]🇺🇸 美国节点`[]🚀 节点选择`[]🇭🇰 香港节点`[]❌ exHK`[]🥵 我的节点
custom_proxy_group=📖 谷歌search`select`[]📖 谷歌`[]🚀 节点选择
custom_proxy_group=📖 学术直连`select`[]🎯 全球直连`[]📖 学术网站`[]📖 学术SELF
custom_proxy_group=📖 学术网站`select`[]📖 学术最优`[]📖 学术SELF`[]🚀 节点选择`[]❌ exHK`[]🇺🇸 美国节点`[]🎯 全球直连`[]🥵 我的节点
custom_proxy_group=📖 学术最优`url-test`(VIP|Taiwan|🇹🇼|Japan|台|日|🇯🇵|新加坡|🇸🇬|马来|🇲🇾|US|美|us|USA|usa|🇺🇸)`http://scholar.google.com`3600,,100
custom_proxy_group=📖 学术SELF`select`(YNU|NENU)
custom_proxy_group=🤖 OpenAI`select`[]❌ exHK`[]🔥 CF最优`[]👑 VIP`[]🇺🇸 美国节点`[]🏠 家宽节点`[]🚀 节点选择
custom_proxy_group=🔥 Cloudflare`select`[]🤖 OpenAI`[]🔥 CF最优`[]📖 谷歌`[]🚀 节点选择`[]🎯 全球直连
custom_proxy_group=📦 github`select`[]📦 github最优`[]🔥 CF最优`[]👑 VIP`[]🇭🇰 香港节点`[]🚀 节点选择`[]🎯 全球直连`[]REJECT
custom_proxy_group=📦 github最优`url-test`(HK|港|hk|Hong|Taiwan|🇹🇼|Japan|台|日|🇯🇵|新加坡|🇸🇬)`https://github.com`3600,,100
custom_proxy_group=📝 vscode`select`[]📝 vscode最优`[]🔥 CF最优`[]🇭🇰 香港节点`[]🚀 节点选择`[]🎯 全球直连`[]REJECT
custom_proxy_group=📝 vscode最优`url-test`(HK|港|hk|Hong|Taiwan|🇹🇼|Japan|台|日|🇯🇵|新加坡|🇸🇬)`https://github.com`3600,,100
custom_proxy_group=🏠 家宽节点`select`[]🏠 家宽最优`(家宽)
custom_proxy_group=🏠 家宽最优`url-test`^(?=.*家宽)(?!.*(香港|HK|Hong[ -]?Kong|🇭🇰)).*$`https://generativelanguage.googleapis.com/v1beta/models`3600,,100
custom_proxy_group=🇺🇸 美国节点`select`[]🇺🇸 美国最优`(US|美|us|USA|usa|🇺🇸)
custom_proxy_group=🇺🇸 美国最优`url-test`(US|美|us|USA|usa|🇺🇸)`https://generativelanguage.googleapis.com/v1beta/models`3600,,100
custom_proxy_group=🇭🇰 香港节点`select`[]🇭🇰 香港最优`(HK|港|香港|hk|Hong)
custom_proxy_group=🇭🇰 香港最优`url-test`(HK|港|香港|hk|Hong)`http://www.gstatic.com/generate_204`3600,,100
custom_proxy_group=❌ exHK`select`[]❌ exHK最优`[]🔥 CF最优`[]🇺🇸 美国节点`(US|USA|usa|United States|America|美国|美|🇺🇸|Singapore|SG|sg|新加坡|狮城|🇸🇬|Japan|JP|jp|日本|日|东京|大阪|🇯🇵|Taiwan|TW|tw|台湾|台|新北|台北|🇹🇼|Korea|KR|kr|South Korea|韩国|韩|首尔|🇰🇷|Canada|CA|ca|加拿大|加|🇨🇦|UK|United Kingdom|Britain|England|英国|英|伦敦|🇬🇧|Australia|AU|au|澳大利亚|澳洲|悉尼|墨尔本|🇦🇺|New Zealand|NZ|nz|新西兰|🇳🇿|Germany|DE|de|德国|德|法兰克福|柏林|🇩🇪|France|FR|fr|法国|法|巴黎|🇫🇷|Netherlands|NL|nl|荷兰|阿姆斯特丹|🇳🇱)
custom_proxy_group=❌ exHK最优`url-test`(US|USA|usa|United States|America|美国|美|🇺🇸|Singapore|SG|sg|新加坡|狮城|🇸🇬|Japan|JP|jp|日本|日|东京|大阪|🇯🇵|Taiwan|TW|tw|台湾|台|新北|台北|🇹🇼|Korea|KR|kr|South Korea|韩国|韩|首尔|🇰🇷|Canada|CA|ca|加拿大|加|🇨🇦|UK|United Kingdom|Britain|England|英国|英|伦敦|🇬🇧|Australia|AU|au|澳大利亚|澳洲|悉尼|墨尔本|🇦🇺|New Zealand|NZ|nz|新西兰|🇳🇿|Germany|DE|de|德国|德|法兰克福|柏林|🇩🇪|France|FR|fr|法国|法|巴黎|🇫🇷|Netherlands|NL|nl|荷兰|阿姆斯特丹|🇳🇱)`https://api.openai.com/v1/models`3600,,100
custom_proxy_group=☎️ 电报`select`[]❌ exHK`[]🇭🇰 香港节点`[]🚀 节点选择`[]🎯 全球直连
custom_proxy_group=💃 TikTok`select`[]🇺🇸 美国节点`[]❌ exHK`[]🚀 节点选择`[]🎯 全球直连
custom_proxy_group=📰 微博`select`[]🎯 全球直连`[]🛑 全球拦截`[]🚀 节点选择
custom_proxy_group=💬 微信`select`[]🎯 全球直连`[]🛑 全球拦截`[]🚀 节点选择
custom_proxy_group=🐧 腾讯`select`[]🎯 全球直连`[]🛑 全球拦截`[]🚀 节点选择
custom_proxy_group=💰 阿里巴巴`select`[]🎯 全球直连`[]🛑 全球拦截`[]🚀 节点选择
custom_proxy_group=📺 批哩批哩`select`[]🎯 全球直连`[]🛑 全球拦截`[]🚀 节点选择
custom_proxy_group=🍠 小红书`select`[]🎯 全球直连`[]🛑 全球拦截`[]🚀 节点选择
custom_proxy_group=🕺 字节跳动`select`[]🎯 全球直连`[]🛑 全球拦截`[]🚀 节点选择
custom_proxy_group=🥭 芒果tv`select`[]🎯 全球直连`[]🛑 全球拦截`[]🚀 节点选择
custom_proxy_group=🎮 米哈游`select`[]🎯 全球直连`[]🛑 全球拦截`[]🚀 节点选择
custom_proxy_group=🥝 爱奇艺`select`[]🎯 全球直连`[]🛑 全球拦截`[]🚀 节点选择
custom_proxy_group=📱 小米`select`[]🎯 全球直连`[]🛑 全球拦截`[]🚀 节点选择
custom_proxy_group=📱 联想`select`[]🎯 全球直连`[]🛑 全球拦截`[]🚀 节点选择
custom_proxy_group=🥵 我的节点`select`(myairport)
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]🎯 全球直连`[]🛑 全球拦截
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🛑 全球拦截

;luck
